package com.android.bringit.utils

enum class EventType {
    UPDATE_MY_QUOTES, QUOTES_UPLOADED, LOGOUT, DELETE_USER, UPDATE_PURCHASE_STATUS, NETWORK_EVENT, UPDATE_LIST, LIST_VIEW_TYPE, FINISH_MY_QUOTE_DETAIL, CHECK_USER_LOGIN, UPLOADING_QUOTES, FAVORITE_QUOTES, MY_FAVORITE_QUOTES, UNLOCK_TEMPLATE, LOGIN_SUCCESS, CONTENT_TAG, POPULAR, HOME

}